SELECT * FROM emp WHERE DEPT_NO='D1' AND PRJ_ID='P3';

SELECT * FROM emp WHERE job IN('MGR') AND DEPT_NO ='D2' OR DEPT_NO ='D3';

SELECT * FROM emp WHERE job='CLRK' AND PRJ_ID ='P3' OR DEPT_NO ='D3';

SELECT * FROM emp WHERE DATE_OF_JOIN<TO_DATE('01-01-2005','DD-MM-YYYY');

SELECT * FROM emp WHERE MGR_ID='6' AND job='CLRK' OR job='A.CLRK';

SELECT * FROM emp WHERE MGR_ID = null;

SELECT * FROM emp WHERE DATE_BIRTH BETWEEN TO_DATE('01-01-1980','DD-MM-YYYY') AND TO_DATE('01-01-1990','DD-MM-YYYY');

SELECT dname, location FROM dept WHERE dname='Marketing' OR dname='Sales' OR dname='Research';

SELECT dname FROM dept WHERE location NOT IN 'MNG' OR location NOT IN 'HYD';

SELECT * FROM emp WHERE PRJ_ID NOT IN 'P1' OR  PRJ_ID NOT IN 'P3' OR  PRJ_ID NOT IN 'P5';